# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: ohnudes <nimatura@student.42barcel>        +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2024/06/12 09:41:14 by ohnudes           #+#    #+#              #
#    Updated: 2024/06/12 20:34:30 by nimatura         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME = ft_display_file

SRC = display_file.c

all: $(NAME)

$(NAME):
	gcc -o $@ $(SRC)

clean:
	rm ft_display_file

fclean: clean

re: fclean all

.PHONY: all clean fclean re
